---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(stringr)
library(lubridate)
library(mmir)
library(bibi2.0)
data("hier.fwmi")
data("attributes.fwmi")
```


```{r}
# Use this only if you have windows 32 bit
# channel <- RODBC::odbcConnect("CBIBI_2017")

# Use this if you have windows 64 bit
library(odbc)
library(DBI)
channel <- dbConnect(odbc(), "CBIBI_2017")

# Set your working directory
setwd("C:/Users/RJepson/Desktop/Access_2_CSV")

#Either import MS Access Database or import individual .csv of the tabs
TAB_EVENT <- read.csv("TAB_EVENT.csv", stringsAsFactors = FALSE)
TAB_STATIONS <- read.csv("TAB_STATIONS.csv", stringsAsFactors = FALSE)
TAB_PROJECT <- read.csv("TAB_PROJECT.csv", stringsAsFactors = FALSE)
TAB_WQ_DATA <- read.csv("TAB_WQ_DATA.csv", stringsAsFactors = FALSE)
TAB_PARAMETER_WQ <- read.csv("TAB_PARAMETER_WQ.csv", stringsAsFactors = FALSE)
TAB_HABITAT_ASSESSMENT <- read.csv("TAB_HABITAT_ASSESSMENT.csv", stringsAsFactors = FALSE)
TAB_HABITAT_PARAMETERS <- read.csv("TAB_HABITAT_PARAMETERS.csv", stringsAsFactors = FALSE)
TAB_TAXONOMIC_COUNT <- read.csv("TAB_TAXONOMIC_COUNT.csv", stringsAsFactors = FALSE)
TAB_HUC_12 <- read.csv("TAB_HUC_12.csv", stringsAsFactors = FALSE)
TAB_PROGRAM <- read.csv("TAB_HUC_12.csv", stringsAsFactors = FALSE)

tab.vec <- c("TAB_EVENT", "TAB_STATIONS", "TAB_PROJECT",
             "TAB_WQ_DATA", "TAB_PARAMETER_WQ", "TAB_HABITAT_ASSESSMENT",
             "TAB_HABITAT_PARAMETERS", "TAB_TAXONOMIC_COUNT",
             "TAB_HUC_12", "TAB_PROGRAM")

# Use the following code only if you are able to use RODBC
# tab.list <- purrr::map(tab.vec, function(tab.i) {
#  RODBC::sqlFetch(channel, tab.i, stringsAsFactors = FALSE) %>% 
#    clean_df()
#}) %>% 
#  set_names(tolower(tab.vec))

#RODBC::odbcCloseAll()

# Use the following code if you are using the ODBC package with windows 64 bit
library(magrittr) 
tab.list <- purrr::map(tab.vec, function(tab.i) {
  dbReadTable(channel, tab.i, stringsAsFactors = FALSE) %>% 
    clean_data_frame()
}) %>% 
  set_names(tolower(tab.vec))

#RODBC::odbcCloseAll()


```

```{r}
tab.list$tab_taxonomic_count <- tab.list$tab_taxonomic_count %>% 
  dplyr::mutate(tsn_final = str_replace_all(tsn_final, "(?<![0-9])0+", "")) %>% 
  left_join(hier.fwmi, by = "tsn_final") %>% 
  prep_taxa()
```

```{r cache=TRUE}
prep.df <- prep_data(tab.list$tab_taxonomic_count,
                     tab.list$tab_wq_data,
                     tab.list$tab_habitat_assessment,
                     tab.list$tab_event,
                     tab.list$tab_stations,
                     tab.list$tab_project,
                     tab.list$tab_huc_12,
                     agg_sample_num = TRUE,
                     development = TRUE)

rm(tab.list)
```

```{r cache=TRUE}
site.class.df <- site_classification(prep.df)
```


```{r cache=TRUE}
taxa.df <- site.class.df %>% 
  ungroup() %>% 
  select(unique_id, category, icprb_bioregion_id, reporting_value,
         final_id, 
         phylum, subphylum, class, subclass,
         order, suborder, family, subfamily, tribe, genus) %>% 
  group_by_at(vars(-reporting_value)) %>% 
  summarize(reporting_value = sum(reporting_value)) %>% 
  ungroup() %>% 
  fill_taxa(final_id, phylum:genus) %>% 
  mutate(final_id = genus) %>% 
  group_by_at(vars(-reporting_value)) %>% 
  summarize(reporting_value = sum(reporting_value)) %>% 
  ungroup()


```

```{r cache=TRUE}
taxa.df <- prob_rarefaction(taxa.df, unique_id, reporting_value, genus, 100)
```

```{r cache=TRUE}
taxa.dev <- taxa.df %>% 
  filter(category %in% c("ref", "deg"))

metrics.df <- taxa.dev %>% 
  select(unique_id, category, icprb_bioregion_id) %>% 
  distinct()

metrics.df <- taxa_seq_parallel(taxa.dev, unique_id, reporting_value,
                                "order", "genus",
                                job = "pct") %>% 
  bind_cols(metrics.df)
```

```{r}

data.table::fwrite(metrics.df, "temp_metrics.csv")
```

