---
title: "R Notebook"
output: html_notebook
---

# Summary


```{r}
cutpoints <- function(x) {
ref.deg.df <- x %>% 
  filter(category %in% c("ref", "deg")) 

cutpoints.df <- map_df(unique(ref.deg.df$spatial), function(i) {
  sub.df <- subset(ref.deg.df, spatial == i)
  final.df <- data.frame(spatial = i, stringsAsFactors = FALSE)
  final.df$cutpoint <- OptimalCutpoints::optimal.cutpoints(final_score ~ category,
                                      data = sub.df,
                                      tag.healthy = "ref",
                                      methods = "SpEqualSe"
                                      )$SpEqualSe$Global$optimal.cutoff$cutoff
  return(final.df)
})

final.df <- left_join(x, cutpoints.df, by = "spatial")

return(final.df)
}

x <- cutpoints(bio.fam.df)

```

```{r}
ce <- function(x) {
  ref.deg.df <- x %>% 
  filter(category %in% c("ref", "deg")) 
  ref.deg.df %>% 
  select(spatial, category, final_score, cutpoint) %>% 
  mutate(class = case_when(
    category == "ref" & final_score >= cutpoint ~ "tp",
    category == "ref" & final_score < cutpoint ~ "fn",
    category == "deg" & final_score < cutpoint ~ "tn",
    category == "deg" & final_score >= cutpoint ~ "fp",
    TRUE ~ "ERROR"
  )) %>% 
  group_by(spatial, class, cutpoint) %>% 
  summarize(count = n()) %>% 
    ungroup() %>% 
  spread(class, count) %>% 
  mutate(ce = (tp + tn) / (tp + fp + tn + fn) * 100)
}
```


```{r}
org.ce <- cutpoints(bio.fam.df) %>% 
  ce() %>% 
  select(spatial, ce)  %>% 
  rename(orginal_ce = ce)
```


```{r}
imp2.df <- ref.imp %>% 
  filter(imp_value >= 2) 
DT::datatable(imp2.df)
```

```{r}
imp.ce <- imp2.df %>% 
  anti_join(bio.fam.df, ., by = c("event_id", "sample_number", "final_score")) %>% 
  cutpoints() %>% 
ce() %>% 
  select(spatial, ce) %>% 
  rename(new_ce = ce) 
```

```{r}
full_join(org.ce, imp.ce, by = "spatial") %>% 
  mutate(change = new_ce - orginal_ce) %>% 
  mutate_if(is.numeric, funs(round(., 2))) %>% 
  arrange(change) %>% 
  DT::datatable(options=list(pageLength = 12)) 
```

```{r}

```

